# Generated by Django 5.0 on 2023-12-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'verbose_name': 'Predicción', 'verbose_name_plural': 'Predicciones'},
        ),
    ]
