# Generated by Django 5.0 on 2024-02-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_detection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='latitude',
            field=models.CharField(default='-12.055747005302624', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='longitude',
            field=models.CharField(default='-77.0856462058371', max_length=20, null=True),
        ),
    ]
