# Generated by Django 5.0 on 2024-07-09 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detection_humidity_detection_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(blank=True, default=0, null=True)),
                ('humidity', models.FloatField(blank=True, default=0, null=True)),
                ('latitude', models.CharField(default='-12.055747005302624', max_length=20, null=True)),
                ('longitude', models.CharField(default='-77.0856462058371', max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detection',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='detection',
            name='temperature',
        ),
        migrations.AddField(
            model_name='detection',
            name='trash_can',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.trashcan'),
        ),
    ]
