# Generated by Django 5.0 on 2024-07-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_trashcan_remove_detection_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='trash_can',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trashcan'),
        ),
    ]
