# Generated by Django 5.0 on 2025-04-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_detection_residue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residue',
            options={'verbose_name': 'Residuo', 'verbose_name_plural': 'Residuos'},
        ),
        migrations.AlterModelOptions(
            name='trashcan',
            options={'verbose_name': 'SmartTachito', 'verbose_name_plural': 'SmartTachitos'},
        ),
    ]
